In [11]:
import pandas as pd
import os
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
from imblearn.over_sampling import SMOTE 
from sklearn.metrics import accuracy_score
from collections import Counter

from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from matplotlib import pyplot

In [2]:
df = pd.read_csv("Nueva global_180722.csv")

nanostring_bx_prosp = df.loc[:, "ACAN_bx": "TBP_bx"]
df_labels = df.loc[:, "BSC ID" : "Diagnosis_simplified"]
df_labels = df_labels.drop("Diagnosis_DEF_4cat", axis=1)
subset = pd.concat([df_labels, nanostring_bx_prosp,], axis=1)
subset = subset.loc[subset["Retrospective1/Prospective2"] == 2]
subset = subset.dropna()
subset = subset.loc[subset["Diagnosis_simplified"].isin(["HB", "HCC", "NOS"])]
subset

BSC ID  Retrospective1/Prospective2 Diagnosis_simplified  ACAN_bx  \
167     171                            2                  HCC   318.29   
168     172                            2                   HB    23.44   
169     173                            2                   HB    44.07   
170     174                            2                   HB    92.08   
171     175                            2                   HB   248.18   
..      ...                          ...                  ...      ...   
331     363                            2                  HCC   191.76   
338     375                            2                   HB   266.05   
339     380                            2                   HB   266.01   
340     386                            2                   HB   143.68   
343     390                            2                   HB   149.60   

      ADAR_bx  ADARB1_bx    AFP_bx  ALDH2_bx  ANGPT2_bx  APCDD1_bx  ...  \
167   1748.35     381.21   2295.44   2211.32      45.41     186.26  ...   
168   1794.59     337.13    267.34   5305.16      56.89     921.45  ...   
169   2222.78     422.76   8484.03   4219.69     119.10     315.81  ...   
170   1828.75     273.52   2908.56   2421.77     217.08     801.26  ...   
171  10735.79     481.26   1181.16   5289.23     338.10    6296.93  ...   
..        ...        ...       ...       ...        ...        ...  ...   
331   5809.28     894.08     52.87   4548.74     285.03     288.30  ...   
338   2154.46     561.09   3683.40   2022.50     612.37   32647.56  ...   
339   1939.72     717.56  30432.76   1544.75     478.42    1853.14  ...   
340   3502.59     537.11   3209.49   7722.82     304.07    7141.68  ...   
343   2059.31     485.85   1264.89   1976.05     532.85   20380.37  ...   

     ACTG1_bx    B2M_bx  EEF1A1_bx   GAPDH_bx  MBD2_bx  NCOR1_bx   PNN_bx  \
167  36545.45  12273.24   57654.07   65182.96   716.09   1026.02  2140.29   
168  17736.22  21511.04   67905.40   12983.08   647.37    543.48  2229.07   
169  16984.33  30481.94   64341.23   24678.02  1127.14    649.27  1941.39   
170  29588.53  60920.25   16573.95    6999.96   151.02    191.93  3182.01   
171  20953.08  60827.22   44292.82   36202.39  1201.67   1141.87  2272.53   
..        ...       ...        ...        ...      ...       ...      ...   
331  13575.93  85542.37   57056.04  104427.17  1254.53    718.50  1494.80   
338  31790.94  34743.43   84619.39   46024.46  1159.97   1317.30  1629.73   
339  23119.62  29761.69   69854.81   53577.06  1243.97    661.46  1646.96   
340  20908.16  48800.93   74987.34   33916.04  1247.33    731.60  1636.05   
343  23040.32  63167.50   65210.43   43769.52  1385.54    595.63  1848.91   

     RHOT2_bx  SNUPN_bx   TBP_bx  
167   1016.71    315.55   441.38  
168    916.82    199.92   264.27  
169    638.10    221.83   321.61  
170  11279.62    246.47   122.92  
171    742.75    251.25   455.63  
..        ...       ...      ...  
331    839.66    333.59  1193.40  
338    561.62    462.60   664.44  
339    627.74    333.36   405.55  
340    587.09    335.64   367.24  
343    537.80    267.46   421.75  

[102 rows x 231 columns]

# Generate synthetic data for unbalance classes

In [3]:
subset = subset.drop(['BSC ID', 'Retrospective1/Prospective2'], axis = 1)
subset

from sklearn.model_selection import train_test_split

X = subset.drop('Diagnosis_simplified', axis=1)
y = subset['Diagnosis_simplified']



In [4]:
sm = SMOTE(k_neighbors=4)

X_sm, y_sm = sm.fit_resample(X, y)

print(f'''Shape of X before SMOTE: {X.shape}
Shape of X after SMOTE: {X_sm.shape}''')

print('\nBalance of positive and negative classes (%):')
print(y_sm.value_counts(normalize=True) * 100)



Shape of X before SMOTE: (102, 228)
Shape of X after SMOTE: (255, 228)

Balance of positive and negative classes (%):
NOS    33.333333
HB     33.333333
HCC    33.333333
Name: Diagnosis_simplified, dtype: float64


In [ ]:
X_sm = X_sm.drop('labels',axis=1)

In [ ]:
test

# Model hyperparameters selction

In [ ]:
# tune regularization for multinomial logistic regression
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from matplotlib import pyplot

#Dataset
X = subset.drop('Diagnosis_simplified', axis=1)
y = subset['Diagnosis_simplified']


# get a list of models to evaluate
def get_models():
	models = dict()
	for p in [0.0, 0.0001, 0.001, 0.01, 0.1, 1.0]:
		# create name for model
		key = '%.4f' % p
		# turn off penalty in some cases
		if p == 0.0:
			# no penalty in this case
			models[key] = LogisticRegression(multi_class='multinomial', solver='lbfgs', penalty='none')
		else:
			models[key] = LogisticRegression(multi_class='multinomial', solver='lbfgs', penalty='l2', C=p)
	return models

# evaluate a give model using cross-validation
def evaluate_model(model, X, y):
	# define the evaluation procedure
	cv = KFold(n_splits=10)
	# evaluate the model
	scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
	return scores


# get the models to evaluate
models = get_models()
# evaluate the models and store results
results, names = list(), list()
for name, model in models.items():
	# evaluate the model and collect the scores
	scores = evaluate_model(model, X, y)
	# store the results
	results.append(scores)
	names.append(name)
	# summarize progress along the way
	print('>%s %.3f (%.3f)' % (name, mean(scores), std(scores)))
# plot model performance for comparison
pyplot.boxplot(results, labels=names, showmeans=True)
pyplot.show()

In [ ]:
# define dataset
# define the multinomial logistic regression model
model = LogisticRegression(multi_class='multinomial', solver='lbfgs', C = 0.1, penalty="l2", max_iter = 1000000)
# fit the model on the whole dataset
model.fit(X_sm, y_sm)


# predict a multinomial probability distribution
yhat = model.predict_proba(X)
# summarize the predicted probabilities
print('Predicted Probabilities: %s' % yhat)

In [ ]:
# predict the class label
yhat = model.predict(X)
# summarize the predicted class
print("Predicted Class: ",  yhat)
print(pd.DataFrame(yhat).iloc[:,0].value_counts())

print("\n")
print(pd.DataFrame(yhat == y).iloc[:,0].value_counts())

score = cross_val_score(model, X, y, scoring='accuracy', n_jobs=-1)
print('>%s %.3f (%.3f)' % (name, mean(score), std(score)))
accuracy_score(y, yhat, sample_weight= y.map(dicc).to_list())


In [22]:
 X_sm["ACAN_bx"]

In [26]:
train_X = np.array( X_sm["ACAN_bx"].sample(frac=0.7,replace=False)).reshape(-1,1)
train_y = y_sm.sample(frac=0.7,replace=False)
test_X= X_sm["ACAN_bx"].drop(train_X.index)
test_y =y_sm.drop(train_y.index)

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [24]:
# define dataset
# define the multinomial logistic regression model
model = LogisticRegression(multi_class='multinomial', solver='lbfgs', C = 0.1, penalty="l2", max_iter = 10000000)
# fit the model on the whole dataset
model.fit(train_X, train_y)


# predict a multinomial probability distribution
#yhat = model.predict_proba()
# summarize the predicted probabilities
#print('Predicted Probabilities: %s' % yhat)
 

ValueError: Expected 2D array, got 1D array instead:
array=[178.27052116  36.54815482  73.24436393  40.22008319  77.30654845
 281.44        31.0603535   39.65649257 183.1550891   83.98975763
  50.75        59.12888347 143.68        52.12        35.9219127
 157.66        59.58578467  37.07510546  58.97242702  55.43892301
  21.93        81.51       698.78        87.23        87.53989701
 119.26253161  65.66413155 318.29        84.69548369 362.96
  81.37073965 104.68037661  45.78        74.09        82.75
  69.58611166  40.71672634 426.53        34.96       148.16
  53.55        58.82        99.01        46.74        64.49
  81.11        73.43316404  86.31112587  97.55        68.13
  81.06828018  59.27145827 318.23087807 266.05        49.82259647
  36.62316852  77.7131685  124.4         52.93861483  33.64
  76.06435998  26.79       119.82128699  75.64495876  65.6835375
  92.08        90.0474429  207.83        34.62        75.21912831
  79.16700249  36.39336849  47.08        43.56641457  77.71849118
  78.71151195  74.00468938 266.01        76.04        72.65866683
  65.58        82.79495135  90.48        81.84        58.70124927
 132.26       140.92828044  49.913401    69.97173343  59.87184963
  35.42       782.09        64.00691265  56.52645322 124.22
 149.6         79.56597661  71.68501508  52.18       117.33826344
 159.63479393  84.74409303 534.37        37.35938073  84.26279058
  74.3149686   86.3517823   59.15401727  52.84064018  81.73
 124.66        42.67725148  90.06       110.81907039  73.63540456
  63.82143048 164.19        42.25710627  34.47868897  49.47
  76.87032901  35.43        79.97323517  41.7765412   38.05
  56.43632973  96.48600798  76.19830424 121.01911559  93.13398327
  89.1         65.20116315 166.75967072 119.74592635  59.66
  84.78       161.39778958  42.62        84.18917627 186.72885031
 159.77679191  36.55390861 329.17        59.02930369  85.00082653
  46.88       143.12557289  80.8         86.66598109 207.64073281
 397.23        80.98029528 117.77       117.33       101.63749557
  62.65        86.11689047  76.59903555 124.49        60.08
 103.41848446 230.6         43.4556468   82.96950594  85.57410146
  52.69879882  53.42        36.09575685  53.10587067 208.77
  45.31166756 248.18        52.15109978 179.39        40.06335019
 106.52        40.52        36.53135678].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [19]:
# predict the class label
yhat = model.predict(test_X)
# summarize the predicted class
print("Predicted Class: ",  yhat)
print(pd.DataFrame(yhat).iloc[:,0].value_counts())

print("\n")
print(pd.DataFrame(yhat == test_y).iloc[:,0].value_counts())


accuracy_score(test_y, yhat)


Predicted Class:  ['NOS' 'NOS' 'HB' 'HCC' 'HB' 'NOS' 'HCC' 'NOS' 'HB' 'HB' 'NOS' 'HB' 'HCC'
 'HB' 'HCC' 'NOS' 'HB' 'HCC' 'HB' 'HB' 'NOS' 'HCC' 'HB' 'HCC' 'HB' 'NOS'
 'NOS' 'HB' 'HB' 'HCC' 'NOS' 'HB' 'HCC' 'HCC' 'HCC' 'NOS' 'HCC' 'HCC' 'HB'
 'HCC' 'HB' 'HB' 'HCC' 'HB' 'HCC' 'HB' 'HCC' 'HCC' 'HB' 'HB' 'NOS' 'HB'
 'HCC' 'HCC' 'HCC' 'HCC' 'HCC' 'HB' 'HB' 'HCC' 'HCC' 'HCC' 'HCC' 'HB' 'HB'
 'HB' 'HCC' 'HCC' 'HCC' 'HCC' 'HB' 'HCC' 'HCC' 'HCC' 'HCC' 'HB' 'HCC']
HCC    36
HB     29
NOS    12
Name: 0, dtype: int64


False    53
True     24
Name: Diagnosis_simplified, dtype: int64


0.3116883116883117

## MLR with nanostring_SR_prosp

In [27]:
df = pd.read_csv("Subsets/Nanostring_SR_prosp.csv", sep= ",")
subset_SR = df.loc[:, "Diagnosis_simplified": "TBP_SR"]
subset_SR = subset_SR.dropna()
print("shape:",subset_SR.shape)
print(subset_SR["Diagnosis_simplified"].value_counts())

shape: (59, 229)
HB     50
HCC     7
NOS     2
Name: Diagnosis_simplified, dtype: int64


In [28]:
X_sr = subset_SR.drop('Diagnosis_simplified', axis=1)
y_sr = subset_SR['Diagnosis_simplified']
bx_names = X.columns
X_sr.columns = bx_names


In [29]:
# define dataset
# define the multinomial logistic regression model
model = LogisticRegression(multi_class='multinomial', solver='lbfgs', C = 0.1, penalty="l2", max_iter = 10000000)
# fit the model on the whole dataset
model.fit(X_sm, y_sm)


# predict a multinomial probability distribution
yhat = model.predict_proba(X_sr)
# summarize the predicted probabilities
print('Predicted Probabilities: %s' % yhat)

Predicted Probabilities: [[1.00000000e+000 2.09427050e-044 3.31906987e-035]
 [1.00000000e+000 1.59644594e-020 8.75676456e-087]
 [1.88141687e-048 7.52425917e-081 1.00000000e+000]
 [8.31816536e-016 1.00000000e+000 1.24921687e-018]
 [6.16573431e-007 9.99999383e-001 3.95911590e-123]
 [1.00000000e+000 6.16736722e-013 3.43632517e-160]
 [1.21548139e-020 8.77153070e-001 1.22846930e-001]
 [1.00000000e+000 2.39333098e-031 9.34310001e-148]
 [1.00000000e+000 8.79376012e-014 1.54937212e-031]
 [9.53376559e-006 9.99990466e-001 6.99907160e-197]
 [1.00000000e+000 1.37709051e-043 1.12654439e-078]
 [9.99999769e-001 2.31357951e-007 1.66743527e-035]
 [1.00000000e+000 2.37159758e-014 1.60188209e-094]
 [1.00000000e+000 8.84414152e-037 0.00000000e+000]
 [1.00000000e+000 3.51050566e-050 1.70224716e-273]
 [2.44616369e-006 9.99997554e-001 0.00000000e+000]
 [8.56090407e-003 9.91439096e-001 6.09732673e-015]
 [1.00000000e+000 8.03622770e-026 5.17820661e-063]
 [7.87012544e-012 1.00000000e+000 5.14998358e-013]
 [1.00

In [31]:
# predict the class label
yhat = model.predict(X_sr)
# summarize the predicted class
print("Predicted Class: ",  yhat)
print(pd.DataFrame(yhat).iloc[:,0].value_counts())

print("\n")
print(pd.DataFrame(yhat == y_sr).iloc[:,0].value_counts())

accuracy_score(y_sr, yhat)

Predicted Class:  ['HB' 'HB' 'NOS' 'HCC' 'HCC' 'HB' 'HCC' 'HB' 'HB' 'HCC' 'HB' 'HB' 'HB'
 'HB' 'HB' 'HCC' 'HCC' 'HB' 'HCC' 'HB' 'HB' 'HCC' 'HB' 'HB' 'HB' 'HB' 'HB'
 'HB' 'HCC' 'HCC' 'HB' 'HB' 'HB' 'HCC' 'HB' 'HB' 'HB' 'HB' 'HB' 'HCC' 'HB'
 'HB' 'HB' 'NOS' 'HB' 'HB' 'HB' 'HB' 'HB' 'HB' 'HB' 'HB' 'HB' 'HCC' 'HCC'
 'HB' 'HB' 'HB' 'HCC']
HB     42
HCC    15
NOS     2
Name: 0, dtype: int64


True     43
False    16
Name: Diagnosis_simplified, dtype: int64


0.7288135593220338